### ISSUE TITLE
Streamlink is not installed or is not reachable at $PATH.

### ISSUE THREAD

**Issue by dthlee** [kpg-anon/streamloop#1]
Hi. I keep getting this error even though I have streamlink installed and I added streamlink/bin to the Path environment variable. Any idea how to troubleshoot? Thanks

**Comment by kpg-anon** [comment]
> Hi. I keep getting this error even though I have streamlink installed and I added streamlink/bin to the Path environment variable. Any idea how to troubleshoot? Thanks

`pip install streamlink`
